# Generated by Django 6.0.8 on 2026-10-02 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_alter_sale_status_salereturn_salereturnitem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('COMPLETED', 'Completed'), ('PARTIALLY_RETURNED', 'Partially returned'), ('FULLY_RETURNED', 'Fully returned')], default='COMPLETED', max_length=28),
        ),
    ]
