# Generated by Django 6.0.8 on 2026-10-01 16:40

import django.db.models.deletion
import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_remove_product_unique_product_sku_per_organization_and_more'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('stock_in', 'Stock in'), ('adjustment_in', 'Adjustment in'), ('adjustment_out', 'Adjustment out')], max_length=20)),
                ('quantity', models.IntegerField()),
                ('previous_quantity', models.PositiveIntegerField()),
                ('new_quantity', models.PositiveIntegerField()),
                ('reason', models.CharField(max_length=500)),
                ('reference_type', models.CharField(blank=True, max_length=50, null=True)),
                ('reference_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='organizations.organization')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='catalog.product')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['organization', '-created_at'], name='inv_org_created_at_idx'), models.Index(fields=['organization', 'product', '-created_at'], name='inv_org_product_created_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity', 0), _negated=True), name='stock_movement_nonzero_quantity'), models.CheckConstraint(condition=models.Q(('previous_quantity__gte', 0), ('new_quantity__gte', 0), ('new_quantity', django.db.models.expressions.CombinedExpression(models.F('previous_quantity'), '+', models.F('quantity')))), name='stock_movement_balances_match'), models.CheckConstraint(condition=models.Q(models.Q(('movement_type__in', ['stock_in', 'adjustment_in']), ('quantity__gt', 0)), models.Q(('movement_type', 'adjustment_out'), ('quantity__lt', 0)), _connector='OR'), name='stock_movement_type_matches_sign')],
            },
        ),
    ]
