# Generated by Django 6.0.8 on 2026-10-02 09:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_remove_product_unique_product_sku_per_organization_and_more'),
        ('inventory', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='stockmovement',
            name='stock_movement_type_matches_sign',
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('stock_in', 'Stock in'), ('adjustment_in', 'Adjustment in'), ('adjustment_out', 'Adjustment out'), ('sale_out', 'Sale out')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('movement_type__in', ['stock_in', 'adjustment_in']), ('quantity__gt', 0)), models.Q(('movement_type__in', ['adjustment_out', 'sale_out']), ('quantity__lt', 0)), _connector='OR'), name='stock_movement_type_matches_sign'),
        ),
    ]
