# Generated by Django 6.0.8 on 2026-10-06

import uuid
from decimal import Decimal

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0002_remove_product_unique_product_sku_per_organization_and_more"),
        ("organizations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Supplier",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                ("phone", models.CharField(blank=True, default="", max_length=50)),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                ("address", models.CharField(blank=True, default="", max_length=500)),
                ("notes", models.CharField(blank=True, default="", max_length=1000)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="suppliers", to="organizations.organization")),
            ],
            options={"ordering": ["name", "-created_at", "-id"]},
        ),
        migrations.CreateModel(
            name="Purchase",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("reference_number", models.CharField(blank=True, default="", max_length=64)),
                ("status", models.CharField(choices=[("DRAFT", "Draft"), ("RECEIVED", "Received"), ("CANCELLED", "Cancelled")], default="DRAFT", max_length=20)),
                ("subtotal", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=14)),
                ("discount", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=14)),
                ("total", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=14)),
                ("notes", models.CharField(blank=True, default="", max_length=1000)),
                ("received_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="purchases_created", to=settings.AUTH_USER_MODEL)),
                ("organization", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="purchases", to="organizations.organization")),
                ("supplier", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="purchases", to="purchases.supplier")),
            ],
            options={"ordering": ["-created_at", "-id"]},
        ),
        migrations.CreateModel(
            name="PurchaseItem",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("product_name", models.CharField(max_length=200)),
                ("product_sku", models.CharField(max_length=100)),
                ("quantity", models.PositiveIntegerField()),
                ("unit_cost", models.DecimalField(decimal_places=2, max_digits=14)),
                ("line_total", models.DecimalField(decimal_places=2, max_digits=14)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("product", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="purchase_items", to="catalog.product")),
                ("purchase", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="items", to="purchases.purchase")),
            ],
            options={"ordering": ["id"]},
        ),
        migrations.AddConstraint(
            model_name="purchase",
            constraint=models.UniqueConstraint(condition=models.Q(("reference_number", ""), _negated=True), fields=("organization", "reference_number"), name="unique_purchase_reference_number_per_organization"),
        ),
        migrations.AddConstraint(
            model_name="purchase",
            constraint=models.CheckConstraint(condition=models.Q(("subtotal__gte", 0), ("discount__gte", 0), ("total__gte", 0)), name="purchase_nonnegative_totals"),
        ),
        migrations.AddConstraint(
            model_name="purchaseitem",
            constraint=models.UniqueConstraint(fields=("purchase", "product"), name="unique_purchase_item_per_product"),
        ),
        migrations.AddConstraint(
            model_name="purchaseitem",
            constraint=models.CheckConstraint(condition=models.Q(("quantity__gt", 0)), name="purchase_item_quantity_positive"),
        ),
        migrations.AddConstraint(
            model_name="purchaseitem",
            constraint=models.CheckConstraint(condition=models.Q(("unit_cost__gte", 0), ("line_total__gte", 0)), name="purchase_item_nonnegative_amounts"),
        ),
    ]
